version: '3'

services:
  db:
    image: postgres
    environment:
        POSTGRES_HOST_AUTH_METHOD: trust

  web:
    build: .
    command: gunicorn -w 1 -k gevent -b 0.0.0.0:8000 mysite.wsgi
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
