version: '3.7'

services:
  web:
    build: .
    command: gunicorn -w 1 -k gevent -b 0.0.0.0:8000 mysite.wsgi
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django_pass
      - POSTGRES_DB=hello_django_dev

volumes:
  postgres_data:
