# Generated by Django 3.0.4 on 2020-03-09 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BookTag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("created_date", models.DateTimeField(blank=True)),
                ("updated_date", models.DateTimeField(blank=True, null=True)),
                ("summary", models.TextField()),
                (
                    "rate",
                    models.IntegerField(
                        choices=[
                            (0, 0),
                            (1, 1),
                            (2, 2),
                            (3, 3),
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                            (8, 8),
                            (9, 9),
                            (10, 10),
                        ]
                    ),
                ),
                ("link", models.CharField(max_length=700)),
                ("author", models.CharField(max_length=200)),
                ("edition", models.CharField(max_length=200)),
                (
                    "tags",
                    models.ManyToManyField(
                        related_name="book_tags", to="books.BookTag"
                    ),
                ),
            ],
        ),
    ]
