# Generated by Django 3.0.4 on 2020-03-09 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Tag", new_name="BlogTag",),
    ]
