# Generated by Django 3.0 on 2020-03-17 18:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("youtube", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="youtubevideo",
            name="created_date",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
